### ISSUE TITLE
iOS Helper never sends badges.

### ISSUE THREAD

**Issue by AlexeyBay** [mideveloper/oyster#10]
Hi, there is no way to add badge to options here
https://github.com/mideveloper/oyster/blob/master/lib/helpers/ios.js#L243
I beleave additional check should look something like 
if (_data.badge) {
    options.badge = _data.badge;
}
because this proprety expected here
https://github.com/mideveloper/oyster/blob/master/lib/helpers/ios.js#L156 

Regards

**Comment by faizulhaque-tp** [comment]
updated

https://github.com/mideveloper/oyster/commit/27740a230ae761ff737d2b8202ff43ba90a9758e

**Comment by AlexeyBay** [comment]
Thanks a lot

**Comment by AlexeyBay** [comment]
One more thing, badge is a number so if(data.badge) wouldn't work if badge === 0
